// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagment.Data;

#nullable disable

namespace UserManagment.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231218065816_AddTableLayouts")]
    partial class AddTableLayouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("UserManagment.Core.Entities.Layout", b =>
                {
                    b.Property<string>("UserLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_login");

                    b.Property<string>("InterfaceType")
                        .HasColumnType("TEXT")
                        .HasColumnName("interface_type");

                    b.Property<string>("SchemaBody")
                        .HasMaxLength(2550000)
                        .HasColumnType("TEXT")
                        .HasColumnName("schema_body")
                        .HasComment("схема в json формате");

                    b.HasKey("UserLogin", "InterfaceType");

                    b.ToTable("t_layouts", t =>
                        {
                            t.HasComment("таблица для хранения схем интерфейсов");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
